### PR TITLE
Fix linter behavior for RPGLEINC files

### LINKED ISSUE #338: RPG Linter firing even on copy books
I thought I heard that the linter wouldn't fire on a source type of RPGLEINC. But it seems to be firing. Is there a setting I need in my Lint configuration?
image

### PR DESCRIPTION
**Pull request by worksofliam**
The linter now correctly ignores specified rules when processing RPGLEINC files, addressing the issue where it was incorrectly firing on these include files. A test case has been added to verify this behavior. Unused log statements have also been removed for cleaner code.

Fixes #338

### CODE REVIEW

**Comment by Gregory1701** [comment]
Thanks @worksofliam ! But, I'm not on v0.26.13 and it's still firing on my source which is RPGLEINC. Did I misunderstand and this isn't out yet?

**Comment by worksofliam** [comment]
@Gregory1701 are you working in a source member, stream file or local?

**Comment by Gregory1701** [comment]
old fashioned source member, my friend. It's in QCPYSRC.

**Comment by worksofliam** [comment]
@Gregory1701 what is the attribute of the member?

**Comment by Gregory1701** [comment]
image

**Comment by worksofliam** [comment]
@Gregory1701 Additional fix, 0.26.14, is out now, which solves this issue. I forgot member attributes in VS Code as not very simple.

**Comment by Gregory1701** [comment]
Thanks @worksofliam , it's better, but still throwing one error. Is that intentional?
image

**Pull request merged**
