### PR TITLE
Fix(getIncludeFromDirective): ignore the comment line

### PR DESCRIPTION
**Pull request by sebCIL**
### Changes

/include or /copy does not work if there is a comment on the line.

### Checklist

* [X] have tested my change
* [X] updated relevant documentation
* [X] Remove any/all `console.log`s I added
* [ ] eslint is not complaining
* [X] have added myself to the contributors' list in the README
* [X] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by worksofliam** [comment]
@sebCIL Can you provide a test case for this?

**Comment by sebCIL** [comment]
I'm not sure where to put the test...
I have made a modification

**Comment by sebCIL** [comment]
is it ok ?

**Comment by worksofliam** [comment]
@sebCIL Sorry for the delay. I will look this week!

**Comment by worksofliam** [comment]
@sebCIL I made one blank new line - thanks for the test case! Let's merge!

**Pull request merged**
