### PR TITLE
Add lowercase directives followup

### PR DESCRIPTION
**Pull request by richardm90**
### Changes

Followup to PR [#283](https://github.com/codefori/vscode-rpgle/pull/283).

1. Removed the `UppercaseDirectives` linter option from the code base.
1. Fixed the use of the new `DirectiveCase` linter option. Most references used `DirectiveCasing`, now all references use `DirectiveCase`. 

### Checklist

* [x] have tested my change
* [ ] updated relevant documentation
* [x] Remove any/all `console.log`s I added
* [x] eslint is not complaining
* [x] have added myself to the contributors' list in the README
* [ ] **for feature PRs**: PR only includes one feature enhancement.

### CODE REVIEW

**Comment by worksofliam** [comment]
@richardm90 Sorry my friend - any chance you can fix the conflicts here? I switched out our ugly test suite for a brand new one using vitest, which works across all platforms now!

**Review by worksofliam — CHANGES_REQUESTED** [review]
Fix conflicts please!

**Comment by richardm90** [comment]
Fixed conflicts

**Review by worksofliam — APPROVED** [review]
Thank you @richardm90 !!

**Pull request merged**
